package com.infosupport.machinelearning.modelmanagement;

import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.MessageSourceAccessor;
import org.springframework.stereotype.Component;

/**
 * Provides a way to format messages generated by the application
 */
@Component
public class Messages {
    private final MessageSourceAccessor messageSourceAccessor;

    /**
     * Initializes a new instance of {@link Messages}
     * @param messageSource Message source to use
     */
    public Messages(MessageSource messageSource) {
        messageSourceAccessor = new MessageSourceAccessor(messageSource, LocaleContextHolder.getLocale());
    }

    /**
     * Gets the formatted value of a message
     *
     * @param identifier Identifier of the message
     * @param args       Arguments to use for formatting the message
     * @return Returns the formatted message
     */
    public String get(String identifier, Object... args) {
        return messageSourceAccessor.getMessage(identifier, args);
    }
}
